package bootz.gaming.bootzbot.domain.teams

import bootz.gaming.bootzbot.domain.teams.teamlinks.Teamlink
import spock.lang.Specification

class TeamTest extends Specification {

    def "Can add a Link"() {
        def teammitglied = new Teammitglied(Set.of(), "B")
        given:
        def team = new Team([new Teammitglied(Set.of(), "A"), teammitglied, new Teammitglied(Set.of(), "C")], [:], Optional.empty())
        def linkId = "asdf"
        def teamlink = new Teamlink("Das ist ein Link", "https://bootz-gaming.com/bootz-gaming-teams/")

        when:
        team.addTeamLink(new AddTeamLinkCommand(teammitglied, linkId, teamlink,false))

        then:
        team.getLinks().containsKey(linkId)
        team.getLinks().get(linkId) == teamlink
    }

    def "Can use a link as custom OPGG"() {
        def teammitglied = new Teammitglied(Set.of(), "B")
        given:
        def team = new Team([new Teammitglied(Set.of(), "A"), teammitglied, new Teammitglied(Set.of(), "C")], [:], Optional.of(new Teamlink("Bootz invite Link", "https://discord.gg/aYumqmdP")))
        def linkId = "asdf"
        def teamlink = new Teamlink("Das ist ein Link", "https://bootz-gaming.com/bootz-gaming-teams/")

        when:
        team.addTeamLink(new AddTeamLinkCommand(teammitglied, linkId, teamlink,true))

        then:
        team.getOpGG() == teamlink.getLink()
    }

    def "OP GG is automatically generated"() {
        given:
        def team = new Team([new Teammitglied(Set.of(), "A"), new Teammitglied(Set.of(), "B"), new Teammitglied(Set.of(), "C")], [:], Optional.empty())
        when:
        def result = team.getOpGG()
        then:
        result == "https://www.op.gg/multisearch/euw?summoners=A,B,C"
    }

    def "Custom OP GG is used over autogenerated"() {
        given:
        def opggLink = new Teamlink("Das opgg des Teams", "https://www.op.gg/multisearch/euw?summoners=z,y,x")
        def team = new Team([new Teammitglied(Set.of(), "A"), new Teammitglied(Set.of(), "B"), new Teammitglied(Set.of(), "C")], ["opGG":opggLink], Optional.of(opggLink))
        when:
        def result = team.getOpGG()
        then:
        result == "https://www.op.gg/multisearch/euw?summoners=z,y,x"
    }
}
